name: Number of covid-19 cases

on:
  schedule:
  - cron: 0 0 * * * #JST 09:00

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python @v2
      with:
	python-version: "3.9"

    - name: Install dependencies
      run: |
	python -m pip install --upgrade pip
	pip install requests

    - name: Run covid19_cases.py
      run: |
	python covid19_cases.py

    - name: Commit and Push
      run: |
        echo commit and push
        git config --local user.email "goo.ishidao@gmail.com"
        git config --local user.name "ishidao0910"
	git add . 
	git commit -m "write today's cases"
	git pull
	git push origin main
