name: write today's jpy-btc

on:
  workflow_dispatch:
  schedule:
  - cron: 0 0 * * * #JST 09:00

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # おまじない

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9" # Pythonのバージョン指定

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          pip install bs4

      - name: Run btc_jpy.py
        run: |
          python btc_jpy.py

      - name: Commit and Push
        run: |
          echo commit and push
          git config --local user.email "goo.ishidao@gmail.com"
          git config --local user.name "ishidao0910"
          git add . 
          git commit -m "write today's btc-jpy"
          git pull
          git push origin main
